theme: jekyll-theme-minimal
title: A wild Līga appeared!
description: <br>Careful, this raw & wild specimen of Līga is very shy and can attack when threatened. Please handle your interaction with care. The below steps may help you get out without any casualties
logo: assets/liga.
show_downloads: "false"
